[package]
name = "fuzz-tests"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
candid = "0.10"
cargo_metadata = "0.20.0"
ic-cdk = "0.18.5"
ic-test = "0.3.1"
pocket-ic = "9.0.2"
serde = "1.0.219"
serde_bytes = "0.11.17"
tokio = { version = "1", features = ["full"] }
convert_case = "0.8.0"